#!/usr/bin/env bash
# install nginx x
sudo apt-get -y  update
sudo apt-get -y install nginx
sudo service ufw start
sudo ufw allow ssh
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html/
echo 'Hello World!' > /var/www/html/index_nginx_debian.html
sudo service nginx restart
