#!/usr/bin/env bash
# fresh install of nginx x
#uninstall previous nginx server if present
prog="nginx"
if command -v "$prog"
	then
		sudo apt-get -y remove nginx nginx-common
		sudo apt-get -y purge nginx nginx-common nginx-core
		sudo apt-get -y autoremove
fi
# install nginx and enable firewall
sudo apt-get -y  update
sudo apt-get -y install nginx
sudo service ufw start
sudo ufw allow ssh
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html/
echo 'Hello World!' > /var/www/html/index.html

#add custom response header
search='server_name _;'
repl="a \ \ \ \ \ \ \ \ add_header X-Served-By \$hostname;"
sudo sed -i "/$search/$repl" /etc/nginx/sites-available/default

# create a redirection configuration
repl="a \ \ \ \ \ \ \ \ location /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}"
sudo sed -i "/$search/$repl" /etc/nginx/sites-available/default

# create a redirection configuration
repl="a \ \ \ \ \ \ \ \ error_page 404 /404.html;"
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/$search/$repl" /etc/nginx/sites-available/default
sudo service nginx restart
