#!/usr/bin/env bash
# configure a web server to listen on port 80
if command -v nginx &> /dev/null;
	then 
	sudo apt -y purge nginx nginx-common nginx-full
	sudo apt -y update
	sudo apt -y install nginx
	sudo service nginx start
else
	sudo apt -y update
	sudo apt -y install nginx
	sudo service nginx start
fi
