#!/usr/bin/env bash
# displays numbers from 1- 100
# if number is multiple of 3 display Fizz
# if number is multiple of 5 display Buzz
# if number is multiple of 3 and 5 display FizzBuzz

i=1
while ((i <= 100))
	do
		if ((i % 3 == 0 && i % 5 == 0))
			then
				echo "FizzBuzz"
		elif (( i % 3 == 0))
			then
				echo "Fizz"
		elif ((i % 5 == 0))
			then
				echo "Buzz"
		else
			echo $((i))
		fi
		((i++))
	done
