#!/usr/bin/env bash
# prints the string hello world to stdout
#+ using a while loop
i=0
while ((i != 10))
do
	if [ $i == 8 ]
		then
			echo "Best School"
			echo "Hi"
	else
			echo "Best School"
	fi
	((i++))
done
