#!/usr/bin/env bash
# prints the string hello world to stdout
#+ using a while loop
i=1
while ((i <= 10))
do
	if ((i == 4))
		then
			echo "bad luck"
	elif ((i == 8))
		then
			echo "good luck"
	else
			echo "Best School"
	fi
	((i++))
done
