#!/usr/bin/env bash
# configure an ubuntu server
cp /etc/hosts ~/hosts.new
sed -i -r  's/^127\.0\.0\.[0-8]/127.0.0.2/' ~/hosts.new
sed -i '$a 8.8.8.8    facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
